---
name: Run Python Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'  
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Run tests with pytest
        run: |
          pytest --cov-branch --cov=./ --cov-report=xml --cov-fail-under 100

      - name: Upload Coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
